using System;
using NokAir.TalkToCeo.Shared.Entities.Common;

namespace NokAir.TalkToCeo.Shared.Dtos
{
    /// <summary>
    /// DTO for broadcasting message summary. This class is intended to provide a concise representation of a broadcast message, typically used in scenarios where a list of broadcast messages is displayed, and only key information such as the subject, display date, and status is needed. It helps to optimize data transfer by excluding detailed content while still conveying essential information about each broadcast message.
    /// </summary>
    public class BroadcastSummaryResponseDto
    {
        /// <summary>
        /// Gets or sets the unique identifier for the broadcast message. This property is essential for distinguishing between different broadcast messages and is typically generated by the system when a new broadcast is created. It allows for easy retrieval, updating, or deletion of specific broadcast messages in the application.
        /// </summary>
        public int TotalUsers { get; set; }

        /// <summary>
        /// Gets or sets the number of users who have read the broadcast message. This property is important for tracking the engagement and reach of the broadcast, as it indicates how many recipients have viewed the message. It can be used to analyze the effectiveness of the broadcast and to make informed decisions about future communications.
        /// </summary>
        public int ReadUsers { get; set; }

        /// <summary>
        /// Gets or sets the number of users who have not read the broadcast message. This property is crucial for understanding the portion of the audience that has yet to engage with the broadcast, allowing for targeted follow-up actions or adjustments in communication strategies to ensure that important messages reach all intended recipients.
        /// </summary>
        public int UnReadUsers { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the message was created. This timestamp is crucial for tracking when the message was created and can be used for sorting, filtering, and displaying the message in chronological order. The CreatedAt property is of type DateTime, which allows it to store both the date and time information accurately. Additionally, this property can be used for auditing purposes to keep a record of when messages were created in the system.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the message was last modified. This timestamp is important for tracking changes to the message and for displaying the message in chronological order based on when it was last updated. The ModifiedAt property is of type DateTime, which allows it to store both the date and time information accurately. This property can also be used for auditing purposes to keep a record of when messages were modified in the system.
        /// </summary>
        public DateTime ModifiedAt { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the message. This information is important for tracking who initiated the communication and can be used for auditing purposes. The CreatedBy property is a string that stores the username of the creator, allowing for easy identification of the message's originator in the system. Similarly, the ModifiedBy property stores the username of the last user who modified the message, providing a clear record of who made changes to the message over time.
        /// </summary>
        public string CreatedBy { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the username of the user who last modified the message. This information is important for tracking who made the most recent changes to the message and can be used for auditing purposes. The ModifiedBy property is a string that stores the username of the last modifier, allowing for easy identification of who updated the message in the system. This helps maintain a clear record of changes and accountability for modifications made to messages over time.
        /// </summary>
        public string ModifiedBy { get; set; } = string.Empty;
    }
}
