using System;
using NokAir.TalkToCeo.Shared.Entities.Common;
using NokAir.TalkToCeo.Shared.Enums;

namespace NokAir.TalkToCeo.Shared.QueryModels.Broadcast
{
    /// <summary>
    /// Represents the result of a query for a user's broadcast messages in the TalkToCeo application. This class contains properties that represent the details of a broadcast message, including its unique identifier, subject, detail, status, pin status, display dates, creation date, CEO information, and read timestamp. It is used to transfer broadcast message data specific to a user between different layers of the application, such as from the backend to the frontend or vice versa.
    /// </summary>
    public class MyBroadcastQueryResult
    {
        /// <summary>
        /// Gets or sets the unique identifier for the broadcast message. This property is essential for distinguishing between different broadcast messages and is typically generated by the system when a new broadcast is created. It allows for easy retrieval, updating, or deletion of specific broadcast messages in the application.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the subject of the broadcast message, which provides a brief summary or title for the content being broadcasted. This field is required and should not be empty, as it helps recipients quickly understand the purpose of the broadcast.
        /// </summary>
        public string Subject { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the detailed content of the broadcast message. This field provides more in-depth information about the broadcast and is optional.
        /// </summary>
        public string Detail { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the current status of the broadcast message. This field helps track the lifecycle of the broadcast, such as whether it is in draft, published, or archived state.
        /// </summary>
        public BroadcastStatus Status { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the broadcast message is pinned. Pinned messages are given higher visibility and are typically displayed at the top of the list.
        /// </summary>
        public bool IsPinned { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the broadcast message should start being displayed. This field is required and helps schedule the broadcast appropriately.
        /// </summary>
        public DateTime? StartDisplayAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the broadcast message should stop being displayed. This field is optional and helps schedule the broadcast appropriately.
        /// </summary>
        public DateTime? ExpireDisplayAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the message was created. This timestamp is crucial for tracking when the message was created and can be used for sorting, filtering, and displaying the message in chronological order. The CreatedAt property is of type DateTime, which allows it to store both the date and time information accurately. Additionally, this property can be used for auditing purposes to keep a record of when messages were created in the system.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the message. This information is important for tracking who initiated the communication and can be used for auditing purposes. The CreatedBy property is a string that stores the username of the creator, allowing for easy identification of the message's originator in the system. Similarly, the ModifiedBy property stores the username of the last user who modified the message, providing a clear record of who made changes to the message over time.
        /// </summary>
        public User Ceo { get; set; } = new User();

        /// <summary>
        /// Gets or sets the date and time when the message was last read by any user. This property is important for tracking the engagement of users with the broadcast message and can be used to determine how many users have read the message and when it was last read. The ReadAt property is of type DateTime?, which allows it to store both the date and time information accurately, while also allowing for null values in cases where the message has not been read by any user.
        /// </summary>
        public DateTime? ReadAt { get; set; }
    }
}
