import { IMail } from '../types/message.model';

export const MOCK_MAILS: IMail[] = [
  {
    id: 1,
    subject: 'Request for annual leave approval',
    message: 'I would like to request annual leave for next Friday.',
    detail: 'Please review and approve my annual leave request.',
    reply: '',
    status: 'PENDING',
    email: 'john.doe@nokair.com',
    jobTitle: 'Software Engineer',
    department: 'Technology',
    fullName: 'John Doe',
    postedAt: '2026-04-08T09:00:00',
    repliedAt: null,
    createdAt: '2026-04-08T09:00:00',
    modifiedAt: '2026-04-08T09:00:00',
    createdBy: 'john.doe',
    modifiedBy: 'john.doe',
  },
  {
    id: 2,
    subject: 'Suggestion for internal communication',
    message: 'I would like to suggest improving communication flow.',
    detail: 'We should have a monthly town hall for all employees.',
    reply: 'Thank you. We will review this suggestion.',
    status: 'REPLIED',
    email: 'jane.smith@nokair.com',
    jobTitle: 'Business Analyst',
    department: 'Business',
    fullName: 'Jane Smith',
    postedAt: '2026-04-07T14:30:00',
    repliedAt: '2026-04-07T16:00:00',
    createdAt: '2026-04-07T14:30:00',
    modifiedAt: '2026-04-07T16:00:00',
    createdBy: 'jane.smith',
    modifiedBy: 'admin',
  },
  {
    id: 3,
    subject: 'Question about project timeline',
    message: 'Could you clarify the expected go-live timeline?',
    detail: 'We need confirmation for planning and resource allocation.',
    reply: '',
    status: 'READ',
    email: 'alex.lee@nokair.com',
    jobTitle: 'Project Coordinator',
    department: 'PMO',
    fullName: 'Alex Lee',
    postedAt: '2026-04-06T11:15:00',
    repliedAt: null,
    createdAt: '2026-04-06T11:15:00',
    modifiedAt: '2026-04-06T13:00:00',
    createdBy: 'alex.lee',
    modifiedBy: 'admin',
  },
  {
    id: 4,
    subject: 'Feedback on employee shuttle service',
    message: 'The current shuttle schedule is very helpful.',
    detail: 'Would it be possible to add one more evening round?',
    reply: '',
    status: 'PENDING',
    email: 'sarah.chan@nokair.com',
    jobTitle: 'Cabin Crew',
    department: 'Operations',
    fullName: 'Sarah Chan',
    postedAt: '2026-04-05T08:45:00',
    repliedAt: null,
    createdAt: '2026-04-05T08:45:00',
    modifiedAt: '2026-04-05T08:45:00',
    createdBy: 'sarah.chan',
    modifiedBy: 'sarah.chan',
  },
  {
    id: 5,
    subject: 'Idea for cost optimization',
    message: 'I have an idea to reduce recurring software costs.',
    detail: 'We may consolidate some unused licenses.',
    reply: 'Good idea. Please prepare a short proposal.',
    status: 'REPLIED',
    email: 'michael.tan@nokair.com',
    jobTitle: 'IT Support',
    department: 'Technology',
    fullName: 'Michael Tan',
    postedAt: '2026-04-04T10:20:00',
    repliedAt: '2026-04-04T15:40:00',
    createdAt: '2026-04-04T10:20:00',
    modifiedAt: '2026-04-04T15:40:00',
    createdBy: 'michael.tan',
    modifiedBy: 'admin',
  },
];
